"""Build SFT data from HumanEval+ / MBPP+ training splits.

Output is chat-format JSONL. Optionally augments the assistant turn with a
chain-of-thought (CoT) generated by a stronger model — CoT meaningfully helps
the 1.5B model on hard problems.
"""

from __future__ import annotations

import argparse
import json

SYSTEM_PROMPT = (
    "You are an expert Python programmer. Write clean, correct code."
)


def build_user_prompt(problem_description: str, function_signature: str) -> str:
    return (
        f"Problem:\n{problem_description}\n\n"
        f"Function signature:\n{function_signature}"
    )


def build_assistant_response(solution: str, cot: str | None = None) -> str:
    if cot:
        return f"{cot}\n```python\n{solution}\n```"
    return f"```python\n{solution}\n```"


def to_sft_record(
    problem_description: str,
    function_signature: str,
    solution: str,
    cot: str | None = None,
) -> dict:
    return {
        "messages": [
            {"role": "system", "content": SYSTEM_PROMPT},
            {
                "role": "user",
                "content": build_user_prompt(
                    problem_description, function_signature
                ),
            },
            {
                "role": "assistant",
                "content": build_assistant_response(solution, cot),
            },
        ]
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", default="data/sft.jsonl")
    parser.add_argument("--with-cot", action="store_true")
    args = parser.parse_args()

    # TODO: load HumanEval+ / MBPP+ training splits via the datasets library,
    # optionally generate CoT with GPT-4o under a strict format prompt, then:
    records: list[dict] = []
    with open(args.out, "w") as f:
        for r in records:
            f.write(json.dumps(r) + "\n")
    print(f"wrote {len(records)} SFT records -> {args.out}")


if __name__ == "__main__":
    main()
